# Generated by Django 6.1 on 2026-08-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "I", "II", "III", "IV"', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "A", "B", "C"', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True, verbose_name='Staff ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_roll_numbers', models.TextField(blank=True, help_text='Enter roll numbers separated by commas or newlines (e.g., 727623BIT001, 727623BIT002)')),
                ('class_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_classes', to='academy.staff')),
                ('mentors', models.ManyToManyField(related_name='mentored_classes', to='academy.staff')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academy.section')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academy.academicyear')),
            ],
            options={
                'verbose_name_plural': 'Student Classes',
                'unique_together': {('year', 'section')},
            },
        ),
    ]
