# Generated by Django 6.1 on 2026-08-29 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('father_occupation', models.CharField(blank=True, max_length=255)),
                ('father_mobile', models.CharField(blank=True, max_length=20)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('mother_occupation', models.CharField(blank=True, max_length=255)),
                ('mother_mobile', models.CharField(blank=True, max_length=20)),
                ('native_location', models.CharField(blank=True, max_length=255)),
                ('communication_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('school_10th', models.CharField(blank=True, max_length=255)),
                ('board_10th', models.CharField(blank=True, max_length=255)),
                ('mark_10th', models.CharField(blank=True, max_length=50)),
                ('percentage_10th', models.CharField(blank=True, max_length=20)),
                ('school_12th', models.CharField(blank=True, max_length=255)),
                ('board_12th', models.CharField(blank=True, max_length=255)),
                ('mark_12th', models.CharField(blank=True, max_length=50)),
                ('percentage_12th', models.CharField(blank=True, max_length=20)),
                ('polytechnic_name', models.CharField(blank=True, max_length=255)),
                ('polytechnic_dept', models.CharField(blank=True, max_length=255)),
                ('diploma_percentage', models.CharField(blank=True, max_length=20)),
                ('educational_gap', models.CharField(blank=True, max_length=255)),
                ('sem1_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem2_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem3_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem4_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem5_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem6_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem7_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('sem8_sgpa', models.CharField(blank=True, default='N/A', max_length=10)),
                ('cgpa', models.CharField(blank=True, max_length=10)),
                ('current_arrears', models.CharField(blank=True, default='0', max_length=10)),
                ('history_of_arrears', models.CharField(blank=True, default='0', max_length=10)),
                ('linkedin_id', models.CharField(blank=True, max_length=255)),
                ('github_id', models.CharField(blank=True, max_length=255)),
                ('leetcode_id', models.CharField(blank=True, max_length=255)),
                ('hackerrank_id', models.CharField(blank=True, max_length=255)),
                ('hackerearth_id', models.CharField(blank=True, max_length=255)),
                ('portfolio_link', models.URLField(blank=True, max_length=500)),
                ('resume_link', models.URLField(blank=True, max_length=500)),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academy.studentclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
