# Generated by Django 6.1 on 2026-08-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_students', to='academy.staff'),
        ),
    ]
