# Generated by Django 6.1 on 2026-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_studentprofile_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('primary_author', models.CharField(max_length=255)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('co_authors', models.TextField(blank=True, help_text='Comma separated list of co-authors')),
                ('author_type', models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student')], default='Student', max_length=20)),
                ('journal', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(default=2025)),
                ('domain', models.CharField(max_length=100)),
                ('citations', models.IntegerField(default=0)),
                ('abstract', models.TextField()),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('keywords', models.TextField(blank=True, help_text='Comma separated keywords')),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('published', 'Published')], default='under_review', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('is_dark_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
