# Generated by Django 6.1 on 2026-08-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_researchpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='under_review', max_length=20),
        ),
    ]
