# Generated by Django 6.1 on 2026-08-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_researchpaper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cited_papers',
            field=models.ManyToManyField(blank=True, related_name='cited_by', to='academy.researchpaper'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='saved_papers',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='academy.researchpaper'),
        ),
    ]
