# Generated by Django 6.1 on 2026-08-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_studentprofile_cited_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='authors_list',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'name': '...', 'email': '...', 'roll_no': '...', 'type': 'Student|Faculty'}]"),
        ),
    ]
