# Generated by Django 6.1 on 2026-08-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_researchpaper_authors_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='research_papers/'),
        ),
    ]
