# Generated by Django 6.1 on 2026-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_staff_college_email_staff_personal_email_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('rejected', 'Rejected')], default='under_review', max_length=20),
        ),
    ]
