# Generated by Django 6.1 on 2026-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_alter_researchpaper_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume_link',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
