# Generated by Django 6.1 on 2026-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_galleryevent_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_repos_count',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hackerearth_problems_count',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hackerrank_badges_count',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_solved_count',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
    ]
