# Generated by Django 6.1 on 2026-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_studentprofile_github_repos_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('leader_roll', models.CharField(help_text='Roll number of the team leader', max_length=50, unique=True)),
                ('leader_name', models.CharField(max_length=255)),
                ('team_members', models.JSONField(default=list, help_text="List of dicts: [{'name': '...', 'roll': '...'}]")),
                ('scenario_allocated', models.CharField(blank=True, max_length=100)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
