# Generated by Django 6.1 on 2026-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_hackathonregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_teams', models.IntegerField(default=50, help_text='Maximum total teams allowed to register')),
                ('max_teams_per_scenario', models.IntegerField(default=10, help_text='Maximum teams allowed per scenario')),
                ('is_registration_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hackathon Settings',
            },
        ),
    ]
