# Generated by Django 6.1 on 2026-09-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_hackathonsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonsettings',
            name='max_teams_per_scenario',
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_teams_scenario_1',
            field=models.IntegerField(default=10, help_text='Maximum teams for SCENARIO 01'),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_teams_scenario_2',
            field=models.IntegerField(default=10, help_text='Maximum teams for SCENARIO 02'),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_teams_scenario_3',
            field=models.IntegerField(default=10, help_text='Maximum teams for SCENARIO 03'),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_teams_scenario_4',
            field=models.IntegerField(default=10, help_text='Maximum teams for SCENARIO 04'),
        ),
        migrations.AddField(
            model_name='hackathonsettings',
            name='max_teams_scenario_5',
            field=models.IntegerField(default=10, help_text='Maximum teams for SCENARIO 05'),
        ),
    ]
