# Generated by Django 6.1 on 2026-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_remove_hackathonsettings_max_teams_per_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonregistration',
            name='is_round_1_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='is_round_2_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='is_round_3_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hackathonregistration',
            name='ppt_file',
            field=models.FileField(blank=True, help_text='Upload Presentation (PDF/PPT)', null=True, upload_to='hackathon_ppts/'),
        ),
    ]
