# Generated by Django 6.1 on 2026-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_hackathonregistration_is_round_1_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonsettings',
            name='is_ppt_time_end',
            field=models.BooleanField(default=False, help_text='If true, teams cannot upload or reupload PPT'),
        ),
    ]
